# Generated by Django 3.2.5 on 2022-06-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20220626_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date',
            field=models.DateField(verbose_name='Data de Realizacao'),
        ),
    ]
