# Generated by Django 3.2.5 on 2022-06-26 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacients', '0001_initial'),
        ('medics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=50, verbose_name='Tipo de Exame')),
                ('date', models.DateField(verbose_name='Data do Exame')),
                ('medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medics.medic')),
                ('pacient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacients.pacient')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['id'],
            },
        ),
    ]
