# Generated by Django 3.2.5 on 2022-06-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='bead',
            field=models.CharField(default=1111, max_length=50, verbose_name='Talao'),
            preserve_default=False,
        ),
    ]
